name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  vet-and-test:
    name: Vet and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: go vet
        env:
          GOOS: js
          GOARCH: wasm
        run: go vet ./...

      - name: Test
        run: go test -v -race -count=1 ./internal/...
